---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unstructured-api
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "unstructured-api:latest",
            "namespace": "unstructured-api"
          },
          "fieldPath": "spec.template.spec.containers[?(@.name==\"api\")].image",
          "paused": false
        }
      ]
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unstructured-api
  template:
    metadata:
      labels:
        app: unstructured-api
    spec:
      serviceAccountName: unstructured-api
      containers:
        - name: api
          image: unstructured-api:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
          ports:
            - name: api
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 512Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
