---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: unstructured-wolfi-base
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations: null
      importPolicy:
        scheduled: true
        importMode: Legacy
      name: latest
      from:
        kind: DockerImage
        name: quay.io/unstructured-io/base-images:wolfi-base-latest
      referencePolicy:
        type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: unstructured-api
spec:
  lookupPolicy:
    local: true
